### ISSUE TITLE
MEASUREMENT MODELS to be differentiable?

### ISSUE THREAD

**Issue by duancaohui** [AshishBora/ambient-gan#2]
Hi, In your paper, It's said "We additionally require f(θ)to be differentiable with respect to its inputs for all θ，I don't what its mean.

It is necessary to derivate D(fθ(G(Z))) by myself? In my problem, I want to add a rician noise to Generative image? I don't know how to add this derivate process to the train.

I review your code, I don't see how to deal with this derivate process, seveal measurement models are quite complex, is it necessary to derivate explicitly?

Another question, if I can obtain the noise data in experiment as the lossy measurements, is it reasonable to add the noise to Generative image just as the role of  f(θ), but the derivate compute may be complex.

**Comment by AshishBora** [comment]
If I understand correctly, you want to sample noise from some distribution, then add it to the image.

In this case, θ is the noise, x is the image, and f_θ(x) = θ + x is just the addition operator. So, the derivative of f_θ(x) is quite simple. This measurement device is already implemented [here](https://github.com/AshishBora/ambient-gan/blob/master/src/commons/measure.py#L251) and you can easily experiment with any desired noise distribution.
